
server:
  port: 8484

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/spring
    username: root
    password : mariadb
  jpa:
    # SQL ??? ?? ? ?? DBMS? ???? ?? ? ??? ?
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      #ddl? ???? ??
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # SQL ??? ? ?? ?? ??? ?? ??
    database: mysql #DBMS ?? ??

logging:
  level:
    root: info
    org.hibernate.sql: debug
    com.study.todoapi : debug

jwt:
  secret: m1It8aLhUInjfD6HXW2FxL6GXcM+gGVxbnA2pzo5gG7BD6wc1mPBXI4LLvp8dOS8UGbSww9p5nc4kXWc0BTtHg==